import {test,expect} from '@playwright/test';
import path from 'node:path';

test('receipt draft stays unposted until reviewed, survives reload and confirms once', async ({page},info)=>{
  const name=`草稿測試-${info.project.name}-${Date.now()}`;
  await page.goto('/');
  await page.getByLabel('帳號',{exact:true}).fill('alice');
  await page.getByLabel('密碼',{exact:true}).fill('synthetic-test-passphrase');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await expect(page.getByRole('button',{name:'收據草稿',exact:true})).toBeVisible();
  const csrf=(await page.context().cookies()).find(c=>c.name==='ft_csrf')!.value;
  const headers={'X-CSRF-Token':csrf,Origin:'http://localhost:5173'};
  const me=await (await page.request.get('/api/v1/auth/me')).json();
  if(!me.settings.setup_completed){const r=await page.request.put('/api/v1/settings',{headers,data:{book_currency:'USD',timezone:'America/Los_Angeles',expected_revision:me.settings.settings_revision}});expect(r.ok()).toBeTruthy();await page.reload();}
  const create=async(route:string,data:unknown)=>{const r=await page.request.post('/api/v1'+route,{headers:{...headers,'Idempotency-Key':crypto.randomUUID()},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json();};
  const account=await create('/accounts',{name,kind:'cash',currency:'USD',opening_balance:'50',opening_on:'2026-01-01'});
  const category=await create('/categories',{name,kind:'expense'});
  await page.getByRole('button',{name:'收據草稿',exact:true}).click();
  await expect(page.getByText('辨識尚未啟用',{exact:true})).toBeVisible();
  await page.locator('input[type=file]').setInputFiles(path.resolve('tests/fixtures/receipt.heic'));
  await page.getByRole('button',{name:'上傳並建立草稿'}).click();
  const dialog=page.getByRole('dialog',{name:'核對收據草稿'});
  await expect(dialog.getByRole('img',{name:'收據預覽'})).toBeVisible();
  await dialog.getByRole('combobox',{name:'收據幣別',exact:true}).selectOption('USD');
  await dialog.getByLabel('金額',{exact:true}).fill('10');
  await dialog.getByLabel('帳務日期').fill('2026-01-05');
  await dialog.getByRole('combobox',{name:'記帳帳戶',exact:true}).selectOption(account.id);
  await dialog.getByRole('combobox',{name:'分類',exact:true}).selectOption(category.id);
  await dialog.getByLabel('商家',{exact:true}).fill(name);
  await expect(dialog.getByRole('button',{name:'確認入帳',exact:true})).toBeDisabled();
  await dialog.getByRole('button',{name:'儲存草稿修改'}).click();
  await expect(dialog.getByText('草稿已儲存，請核對後確認入帳。')).toBeVisible();
  const accountsBefore=await (await page.request.get('/api/v1/accounts')).json();
  expect(accountsBefore.find((a:{id:string})=>a.id===account.id).balance).toBe('50');
  await dialog.getByRole('button',{name:'關閉草稿'}).click();
  await page.reload();
  await page.getByRole('button',{name:'收據草稿',exact:true}).click();
  await page.locator('.draft-card').filter({hasText:name}).click();
  await expect(dialog.getByLabel('金額',{exact:true})).toHaveValue('10');
  expect(await dialog.evaluate(n=>n.scrollWidth>n.clientWidth)).toBe(false);
  await dialog.evaluate(n=>{n.scrollTop=0;});
  await page.screenshot({path:info.outputPath('capture-review.png'),fullPage:false});
  await dialog.getByLabel('我已核對提醒與收據，確認填寫金額正確').check();
  await dialog.getByRole('button',{name:'確認入帳',exact:true}).click();
  await expect(dialog.getByText('已確認入帳，收據已附在交易上。')).toBeVisible();
  const rows=await (await page.request.get('/api/v1/capture/drafts?include_closed=true')).json();
  const row=rows.find((d:{proposal:{merchant:string}})=>d.proposal.merchant===name);
  const again=await page.request.post(`/api/v1/capture/drafts/${row.id}/confirm`,{headers,data:{expected_revision:row.revision-1,acknowledge_warnings:true}});
  expect(again.ok()).toBeTruthy();
  const accountsAfter=await (await page.request.get('/api/v1/accounts')).json();
  expect(accountsAfter.find((a:{id:string})=>a.id===account.id).balance).toBe('40');
  const attached=await (await page.request.get(`/api/v1/transactions/${row.confirmed_transaction_id}/attachments`)).json();
  expect(attached).toHaveLength(1);
});
