import {test,expect} from '@playwright/test';
import path from 'node:path';

test('receipt items survive review, confirm once, search history and correct posted prices', async ({page},info)=>{
  // Simulate an embedded browser suppressing JS confirm. Page-owned decisions must still work.
  await page.addInitScript(()=>{window.confirm=()=>false;});
  const name=`草稿測試-${info.project.name}-${Date.now()}`;
  await page.goto('/');
  await page.getByLabel('帳號',{exact:true}).fill('alice');
  await page.getByLabel('密碼',{exact:true}).fill('synthetic-test-passphrase');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await expect(page.getByRole('button',{name:'收據草稿',exact:true})).toBeVisible();
  const csrf=(await page.context().cookies()).find(c=>c.name==='ft_csrf')!.value;
  const headers={'X-CSRF-Token':csrf,Origin:'http://localhost:5173'};
  const me=await (await page.request.get('/api/v1/auth/me')).json();
  if(!me.settings.setup_completed){const r=await page.request.put('/api/v1/settings',{headers,data:{book_currency:'USD',timezone:'America/Los_Angeles',expected_revision:me.settings.settings_revision}});expect(r.ok()).toBeTruthy();await page.reload();}
  const create=async(route:string,data:unknown)=>{const r=await page.request.post('/api/v1'+route,{headers:{...headers,'Idempotency-Key':crypto.randomUUID()},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json();};
  const account=await create('/accounts',{name,kind:'cash',currency:'USD',opening_balance:'50',opening_on:'2026-01-01'});
  const categoryName=`生活 ${name}`, childName=`用品 ${name}`, incomeName=`收入 ${name}`;
  const productName=`日常牛奶 ${name}`, alias=`Fresh Dairy ${name}`;
  await page.getByRole('button',{name:'商品紀錄',exact:true}).click();
  await page.getByText('管理商品名稱與別名',{exact:true}).click();
  await page.getByLabel('商品名稱',{exact:true}).fill(productName);
  await page.getByRole('button',{name:'清空／新增另一商品'}).click();
  const discardProduct=page.getByRole('dialog',{name:'捨棄商品修改？'});
  await discardProduct.getByRole('button',{name:'繼續編輯'}).click();
  await expect(page.getByLabel('商品名稱',{exact:true})).toHaveValue(productName);
  await page.getByLabel('商品別名（每行一個，最多 30 個）').fill(alias);
  await page.getByRole('button',{name:'建立商品',exact:true}).click();
  await expect(page.getByText('商品與別名已儲存。請在收據品項中選擇對應商品，既有品項不會自動歸類。')).toBeVisible();
  const catalog=await (await page.request.get('/api/v1/products/catalog')).json();
  const product=catalog.find((p:{name:string})=>p.name===productName);
  await page.screenshot({path:info.outputPath('product-catalog.png'),fullPage:true});
  await page.getByRole('button',{name:'收據草稿',exact:true}).click();
  await expect(page.getByText('辨識尚未啟用',{exact:true})).toBeVisible();
  // Synthetic parsed fixture: show the origin of a prefill and preserve a manual override.
  const currencyMerchant=`合成幣別測試 ${info.project.name}`;
  await page.locator('.draft-card').filter({hasText:currencyMerchant}).click();
  const currencyDialog=page.getByRole('dialog',{name:'核對收據草稿'});
  await expect(currencyDialog.getByRole('combobox',{name:'收據幣別',exact:true})).toHaveValue('USD');
  await expect(currencyDialog.getByRole('note')).toContainText('地區推測');
  await expect(currencyDialog.getByRole('note')).toContainText('Palo Alto CA 94301');
  await currencyDialog.getByRole('combobox',{name:'收據幣別',exact:true}).selectOption('TWD');
  await expect(currencyDialog.getByLabel('金額',{exact:true})).toHaveValue('10.50');
  await currencyDialog.getByRole('button',{name:'儲存草稿修改'}).click();
  await expect(currencyDialog.getByText('草稿已儲存，請核對後確認入帳。')).toBeVisible();
  await currencyDialog.getByRole('button',{name:'完成／關閉'}).click();
  await page.locator('.draft-card').filter({hasText:currencyMerchant}).click();
  await expect(currencyDialog.getByRole('combobox',{name:'收據幣別',exact:true})).toHaveValue('TWD');
  await expect(currencyDialog.getByRole('note')).toContainText('初次辨識');
  await expect(currencyDialog.getByLabel('金額',{exact:true})).toHaveValue('10.50');
  await page.screenshot({path:info.outputPath('currency-inference.png')});
  await currencyDialog.getByRole('button',{name:'完成／關閉'}).click();
  await page.locator('input[type=file]').setInputFiles(path.resolve('tests/fixtures/receipt.heic'));
  await page.getByRole('button',{name:'上傳並建立草稿'}).click();
  const dialog=page.getByRole('dialog',{name:'核對收據草稿'});
  await expect(dialog.getByRole('img',{name:'收據預覽'})).toBeVisible();
  await expect(dialog.getByRole('button',{name:'新增品項'})).toBeDisabled();
  await dialog.getByRole('combobox',{name:'收據幣別',exact:true}).selectOption('USD');
  await dialog.getByLabel('金額',{exact:true}).fill('10');
  await dialog.getByLabel('帳務日期').fill('2026-01-05');
  await dialog.getByRole('combobox',{name:'記帳帳戶',exact:true}).selectOption(account.id);
  await dialog.getByLabel('商家',{exact:true}).fill(name);
  await dialog.getByRole('button',{name:'新增分類',exact:true}).click();
  const categoryDialog=page.getByRole('dialog',{name:'新增分類',exact:true});
  await expect(categoryDialog.getByLabel('收支類型')).toHaveValue('expense');
  await expect(categoryDialog.getByLabel('收支類型')).toBeDisabled();
  await page.keyboard.press('Escape');
  await expect(categoryDialog).not.toBeVisible();
  await expect(dialog.getByLabel('商家',{exact:true})).toHaveValue(name);
  await dialog.getByRole('button',{name:'新增分類',exact:true}).click();
  await categoryDialog.getByLabel('分類名稱').fill(categoryName);
  // A rejected category request must retain the name and the underlying receipt.
  await page.route('**/api/v1/categories',async route=>{
    if(route.request().method()==='POST')await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({code:'synthetic_unavailable',message:'合成分類服務暫時無法回應'})});
    else await route.continue();
  });
  await categoryDialog.getByRole('button',{name:'儲存分類'}).click();
  await expect(categoryDialog.getByRole('alert')).toContainText('合成分類服務暫時無法回應');
  await expect(categoryDialog.getByLabel('分類名稱')).toHaveValue(categoryName);
  await page.unroute('**/api/v1/categories');
  await categoryDialog.getByRole('button',{name:'儲存分類'}).click();
  await expect(categoryDialog).not.toBeVisible();
  const categories=await (await page.request.get('/api/v1/categories')).json();
  const category=categories.find((c:{name:string})=>c.name===categoryName);
  expect(categories.filter((c:{name:string})=>c.name===categoryName)).toHaveLength(1);
  await expect(dialog.getByRole('combobox',{name:'分類',exact:true})).toHaveValue(category.id);
  await expect(dialog.getByLabel('金額',{exact:true})).toHaveValue('10');
  await expect(dialog.getByLabel('商家',{exact:true})).toHaveValue(name);
  await dialog.getByRole('combobox',{name:'收支類型',exact:true}).selectOption('income');
  await expect(dialog.getByRole('combobox',{name:'分類',exact:true}).locator('option')).not.toContainText([categoryName]);
  await dialog.getByRole('button',{name:'新增分類',exact:true}).click();
  await expect(categoryDialog.getByLabel('收支類型')).toHaveValue('income');
  await expect(categoryDialog.getByLabel('上層分類').locator('option')).not.toContainText([categoryName]);
  await categoryDialog.getByLabel('分類名稱').fill(incomeName);
  await categoryDialog.getByRole('button',{name:'儲存分類'}).click();
  await expect(categoryDialog).not.toBeVisible();
  await dialog.getByRole('combobox',{name:'收支類型',exact:true}).selectOption('expense');
  await expect(dialog.getByRole('combobox',{name:'分類',exact:true}).locator('option')).not.toContainText([incomeName]);
  await dialog.getByRole('combobox',{name:'分類',exact:true}).selectOption(category.id);
  await dialog.getByRole('button',{name:'加入分類分攤',exact:true}).click();
  await expect(dialog.getByRole('combobox',{name:'分攤分類 1',exact:true})).toHaveValue(category.id);
  await expect(dialog.getByLabel('分攤金額 1',{exact:true})).toHaveValue('10');
  await expect(dialog.getByLabel('分攤金額 2',{exact:true})).toHaveValue('');
  await dialog.getByRole('button',{name:'新增分類至分攤 2'}).click();
  await categoryDialog.getByLabel('分類名稱').fill(childName);
  await categoryDialog.getByLabel('上層分類').selectOption(category.id);
  await page.screenshot({path:info.outputPath('receipt-add-category.png')});
  await categoryDialog.getByRole('button',{name:'儲存分類'}).click();
  await expect(categoryDialog).not.toBeVisible();
  const child=(await (await page.request.get('/api/v1/categories')).json()).find((c:{name:string})=>c.name===childName);
  expect(child.parent_id).toBe(category.id);
  await expect(dialog.getByRole('combobox',{name:'分攤分類 2',exact:true})).toHaveValue(child.id);
  await dialog.getByRole('button',{name:'移除分攤1',exact:true}).click();
  await expect(dialog.getByRole('combobox',{name:'分類',exact:true})).toHaveValue(child.id);
  await expect(dialog.getByLabel('金額',{exact:true})).toHaveValue('10');
  await dialog.getByRole('button',{name:'加入分類分攤',exact:true}).click();
  await dialog.getByRole('combobox',{name:'分攤分類 2',exact:true}).selectOption(category.id);
  await dialog.getByLabel('分攤金額 1',{exact:true}).fill('4');
  await dialog.getByLabel('分攤金額 2',{exact:true}).fill('6');
  await dialog.getByRole('button',{name:'新增分類至分攤 1'}).click();
  await categoryDialog.getByRole('button',{name:'取消',exact:true}).click();
  await expect(dialog.getByLabel('分攤金額 1',{exact:true})).toHaveValue('4');
  await expect(dialog.getByRole('combobox',{name:'分攤分類 1',exact:true})).toHaveValue(child.id);
  await dialog.getByLabel('分攤金額 2',{exact:true}).scrollIntoViewIfNeeded();
  expect(await dialog.evaluate(n=>n.scrollWidth>n.clientWidth)).toBe(false);
  await page.screenshot({path:info.outputPath('receipt-category-splits.png')});
  await expect(dialog.getByRole('button',{name:'確認入帳',exact:true})).toBeDisabled();
  await dialog.getByRole('button',{name:'儲存草稿修改'}).click();
  await expect(dialog.getByText('草稿已儲存，請核對後確認入帳。')).toBeVisible();
  await dialog.getByRole('button',{name:'新增品項'}).click();
  await dialog.getByLabel('品名 1',{exact:true}).fill(`牛奶 ${name}`);
  await dialog.getByRole('combobox',{name:'對應商品 1',exact:true}).selectOption(product.id);
  await dialog.getByLabel('數量 1',{exact:true}).fill('2');
  await dialog.getByLabel('單位／規格 1',{exact:true}).fill('瓶／1L');
  await dialog.getByLabel('單價 1',{exact:true}).fill('5');
  await dialog.getByLabel('列金額 1',{exact:true}).fill('10');
  await expect(dialog.getByRole('button',{name:'確認入帳',exact:true})).toBeDisabled();
  await dialog.getByRole('button',{name:'關閉草稿'}).click();
  const leave=page.getByRole('dialog',{name:'離開收據核對？'});
  await expect(leave).toBeVisible();
  await expect(leave.getByRole('button',{name:'繼續編輯'})).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(leave).not.toBeVisible();
  await dialog.getByRole('button',{name:'完成／關閉',exact:true}).click();
  await leave.getByRole('button',{name:'繼續編輯'}).click();
  await expect(dialog.getByLabel('品名 1',{exact:true})).toHaveValue(`牛奶 ${name}`);
  await dialog.getByRole('button',{name:'重新載入品項',exact:true}).click();
  const reloadItems=page.getByRole('dialog',{name:'重新載入品項？'});
  await expect(reloadItems).toBeVisible();
  await reloadItems.getByRole('button',{name:'繼續編輯'}).click();
  await dialog.getByRole('button',{name:'完成／關閉',exact:true}).click();
  await page.screenshot({path:info.outputPath('discard-review.png')});
  await leave.getByRole('button',{name:'捨棄修改並關閉'}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.locator('.draft-card').filter({hasText:name}).click();
  await expect(dialog.getByLabel('品名 1',{exact:true})).toHaveCount(0);
  await dialog.getByRole('button',{name:'新增品項'}).click();
  await dialog.getByLabel('品名 1',{exact:true}).fill(`牛奶 ${name}`);
  await dialog.getByRole('combobox',{name:'對應商品 1',exact:true}).selectOption(product.id);
  await dialog.getByLabel('數量 1',{exact:true}).fill('2');
  await dialog.getByLabel('單位／規格 1',{exact:true}).fill('瓶／1L');
  await dialog.getByLabel('單價 1',{exact:true}).fill('5');
  await dialog.getByLabel('列金額 1',{exact:true}).fill('10');
  await dialog.getByLabel('我已逐項核對原收據；不確定的數值已留白').check();
  await dialog.getByRole('button',{name:'儲存已核對品項'}).click();
  await expect(dialog.getByText('品項已核對；確認入帳後即可在「商品紀錄」搜尋。')).toBeVisible();
  await dialog.getByLabel('品名 1',{exact:true}).fill('尚未儲存，重新載入應捨棄');
  await dialog.getByRole('button',{name:'重新載入品項',exact:true}).click();
  await reloadItems.getByRole('button',{name:'捨棄修改並重新載入'}).click();
  await expect(dialog.getByLabel('品名 1',{exact:true})).toHaveValue(`牛奶 ${name}`);
  await dialog.getByLabel('我已逐項核對原收據；不確定的數值已留白').check();
  await dialog.getByLabel('我已逐項核對原收據；不確定的數值已留白').uncheck();
  const accountsBefore=await (await page.request.get('/api/v1/accounts')).json();
  expect(accountsBefore.find((a:{id:string})=>a.id===account.id).balance).toBe('50');
  const historyBefore=await (await page.request.get('/api/v1/products/history?q='+encodeURIComponent(name))).json();
  expect(historyBefore.items).toHaveLength(0);
  await dialog.getByRole('button',{name:'關閉草稿'}).click();
  await page.reload();
  await page.getByRole('button',{name:'收據草稿',exact:true}).click();
  await page.locator('.draft-card').filter({hasText:name}).click();
  await expect(dialog.getByLabel('金額',{exact:true})).toHaveValue('10');
  await expect(dialog.getByRole('combobox',{name:'分攤分類 1',exact:true})).toHaveValue(child.id);
  await expect(dialog.getByLabel('分攤金額 1',{exact:true})).toHaveValue('4');
  await expect(dialog.getByRole('combobox',{name:'分攤分類 2',exact:true})).toHaveValue(category.id);
  await expect(dialog.getByLabel('分攤金額 2',{exact:true})).toHaveValue('6');
  expect(await dialog.evaluate(n=>n.scrollWidth>n.clientWidth)).toBe(false);
  await dialog.evaluate(n=>{n.scrollTop=0;});
  await page.screenshot({path:info.outputPath('capture-review.png'),fullPage:false});
  await dialog.getByLabel('我已核對提醒與收據，確認填寫金額正確').check();
  await dialog.getByRole('button',{name:'確認入帳',exact:true}).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByText('已確認入帳，收據已附在交易上。')).toBeVisible();
  const rows=await (await page.request.get('/api/v1/capture/drafts?include_closed=true')).json();
  const row=rows.find((d:{proposal:{merchant:string}})=>d.proposal.merchant===name);
  const again=await page.request.post(`/api/v1/capture/drafts/${row.id}/confirm`,{headers,data:{expected_revision:row.revision-1,acknowledge_warnings:true}});
  expect(again.ok()).toBeTruthy();
  const accountsAfter=await (await page.request.get('/api/v1/accounts')).json();
  expect(accountsAfter.find((a:{id:string})=>a.id===account.id).balance).toBe('40');
  const postedPage=await (await page.request.get(`/api/v1/transactions?start=2026-01-01&end_exclusive=2026-02-01&account_id=${account.id}`)).json();
  const posted=postedPage.items.find((t:{id:string})=>t.id===row.confirmed_transaction_id);
  expect(posted.splits).toHaveLength(2);
  expect(posted.splits).toEqual(expect.arrayContaining([{category_id:child.id,amount:'4'},{category_id:category.id,amount:'6'}]));
  const attached=await (await page.request.get(`/api/v1/transactions/${row.confirmed_transaction_id}/attachments`)).json();
  expect(attached).toHaveLength(1);
  await page.getByRole('button',{name:'商品紀錄',exact:true}).click();
  await page.getByLabel('搜尋商品',{exact:true}).fill(alias.toUpperCase());
  await page.getByRole('button',{name:'搜尋',exact:true}).click();
  await expect(page.locator('.purchase-card')).toHaveCount(1);
  await expect(page.locator('.purchase-card').getByRole('heading',{name:`牛奶 ${name}`})).toBeVisible();
  await expect(page.locator('.purchase-card').getByText(`對應商品：${productName}（手動連結）`)).toBeVisible();
  await page.getByRole('button',{name:'查看收據／修正品項'}).click();
  await expect(dialog.getByRole('combobox',{name:'對應商品 1',exact:true})).toHaveValue(product.id);
  await expect(dialog.getByRole('img',{name:'收據預覽'})).toBeVisible();
  await dialog.getByLabel('品名 1',{exact:true}).fill(`燕麥奶 ${name}`);
  await dialog.getByLabel('單價 1',{exact:true}).fill('4.5');
  await dialog.getByLabel('列金額 1',{exact:true}).fill('9');
  await dialog.getByLabel('品項備註 1',{exact:true}).fill('合成折扣核對');
  await dialog.getByLabel('我已逐項核對原收據；不確定的數值已留白').check();
  await page.clock.install();
  let release!:()=>void;
  const blocked=new Promise<void>(resolve=>{release=resolve;});
  await page.route('**/capture/drafts/*/items',async route=>{
    if(route.request().method()==='PUT'){await blocked;await route.abort().catch(()=>{});}else await route.continue();
  });
  const pending=page.waitForRequest(r=>r.url().endsWith('/items')&&r.method()==='PUT');
  await dialog.getByRole('button',{name:'儲存已核對品項'}).click();await pending;
  await expect(dialog.getByRole('button',{name:'關閉草稿'})).toBeDisabled();
  await page.clock.fastForward(31000);
  await expect(dialog.getByRole('alert')).toContainText('連線等待逾時');
  await expect(dialog.getByRole('button',{name:'關閉草稿'})).toBeEnabled();
  await expect(dialog.getByLabel('單價 1',{exact:true})).toHaveValue('4.5');
  release();await page.unroute('**/capture/drafts/*/items');
  await dialog.getByRole('button',{name:'儲存已核對品項'}).click();
  await expect(dialog.getByText('品項已核對，可到「商品紀錄」搜尋。帳務金額未改動。')).toBeVisible();
  expect(await dialog.evaluate(el=>el.scrollWidth>el.clientWidth)).toBe(false);
  await dialog.locator('.item-review').scrollIntoViewIfNeeded();
  await expect(dialog.getByRole('button',{name:'關閉草稿'})).toBeInViewport();
  await page.screenshot({path:info.outputPath('item-review.png')});
  await dialog.getByRole('button',{name:'關閉草稿'}).click();
  await expect(page.locator('.purchase-card').getByRole('heading',{name:`燕麥奶 ${name}`})).toBeVisible();
  await expect(page.locator('.purchase-card').getByText('4.5',{exact:true})).toBeVisible();
  const afterCorrection=await (await page.request.get('/api/v1/accounts')).json();
  expect(afterCorrection.find((a:{id:string})=>a.id===account.id).balance).toBe('40');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false);
  await page.screenshot({path:info.outputPath('product-history.png'),fullPage:true});
  await page.reload();
  await page.getByRole('button',{name:'商品紀錄',exact:true}).click();
  await page.getByLabel('搜尋商品',{exact:true}).fill(`燕麥奶 ${name}`);
  await page.getByRole('button',{name:'搜尋',exact:true}).click();
  await expect(page.locator('.purchase-card')).toHaveCount(1);
  await page.getByText('管理商品名稱與別名',{exact:true}).click();
  await page.getByLabel('選擇要編輯的商品').selectOption(product.id);
  const newAlias=`Oat Drink ${name}`;
  await page.getByLabel('商品別名（每行一個，最多 30 個）').fill(newAlias);
  await page.getByRole('button',{name:'儲存商品修改',exact:true}).click();
  await expect(page.getByText('商品與別名已儲存。請在收據品項中選擇對應商品，既有品項不會自動歸類。')).toBeVisible();
  await page.getByLabel('搜尋商品',{exact:true}).fill(alias);
  await page.getByRole('button',{name:'搜尋',exact:true}).click();
  await expect(page.locator('.purchase-card')).toHaveCount(0);
  await page.getByLabel('搜尋商品',{exact:true}).fill(newAlias);
  await page.getByRole('button',{name:'搜尋',exact:true}).click();
  await expect(page.locator('.purchase-card')).toHaveCount(1);
  await page.getByRole('button',{name:'收據草稿',exact:true}).click();
  await page.getByLabel('記帳內容',{exact:true}).fill(`合成取消測試 ${name}`);
  await page.getByRole('button',{name:'建立文字草稿',exact:true}).click();
  await expect(dialog).toBeVisible();
  await dialog.getByLabel('商家',{exact:true}).fill(`合成取消 ${name}`);
  await dialog.getByRole('button',{name:'儲存草稿修改'}).click();
  await expect(dialog.getByText('草稿已儲存，請核對後確認入帳。')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
  await page.locator('.draft-card').filter({hasText:`合成取消 ${name}`}).click();
  await dialog.getByRole('button',{name:'取消這份草稿',exact:true}).click();
  await dialog.getByRole('button',{name:'返回',exact:true}).click();
  await expect(dialog).toBeVisible();
  await dialog.getByRole('button',{name:'取消這份草稿',exact:true}).click();
  await dialog.getByRole('button',{name:'確定取消草稿',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByText('草稿已取消，沒有新增交易。')).toBeVisible();

  // Each new draft gets advice, but the user must choose and confirm it.
  await page.route('**/category-suggestions',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({code:'synthetic_unavailable',message:'合成建議暫時無法提供'})}));
  await page.getByLabel('記帳內容',{exact:true}).fill(`Membership 合成會員費 ${name}`);
  await page.getByRole('button',{name:'建立文字草稿',exact:true}).click();
  const advice=dialog.getByRole('region',{name:'建議分類',exact:true});
  await expect(advice.getByRole('status')).toContainText('合成建議暫時無法提供');
  await expect(dialog.getByRole('combobox',{name:'分類',exact:true})).toHaveValue('');
  await expect(dialog.getByRole('combobox',{name:'分類',exact:true})).toBeEnabled();
  await page.unroute('**/category-suggestions');
  await advice.getByRole('button',{name:'更新建議'}).click();
  await expect(advice.getByText('會員／訂閱',{exact:true})).toBeVisible();
  await advice.getByRole('button',{name:'建立建議分類 會員／訂閱',exact:true}).click();
  await expect(categoryDialog.getByLabel('分類名稱')).toHaveValue('會員／訂閱');
  await categoryDialog.getByRole('button',{name:'取消',exact:true}).click();
  await expect(dialog.getByRole('combobox',{name:'分類',exact:true})).toHaveValue('');
  await advice.getByRole('button',{name:'建立建議分類 會員／訂閱',exact:true}).click();
  const memberCategory=`會員費 ${name}`, memberShop=`合成會員商店 ${name}`;
  await categoryDialog.getByLabel('分類名稱').fill(memberCategory);
  await categoryDialog.getByRole('button',{name:'儲存分類',exact:true}).click();
  await expect(categoryDialog).not.toBeVisible();
  const memberId=await dialog.getByRole('combobox',{name:'分類',exact:true}).inputValue();
  expect(memberId).toBeTruthy();
  await dialog.getByRole('combobox',{name:'收據幣別',exact:true}).selectOption('USD');
  await dialog.getByRole('combobox',{name:'記帳帳戶',exact:true}).selectOption(account.id);
  await dialog.getByLabel('金額',{exact:true}).fill('1');
  await dialog.getByLabel('帳務日期').fill('2026-01-08');
  await dialog.getByLabel('商家',{exact:true}).fill(memberShop);
  await dialog.getByRole('button',{name:'儲存草稿修改'}).click();
  await expect(dialog.getByText('草稿已儲存，請核對後確認入帳。')).toBeVisible();
  await dialog.getByLabel('我已核對提醒與收據，確認填寫金額正確').check();
  await dialog.getByRole('button',{name:'確認入帳',exact:true}).click();
  await expect(dialog).not.toBeVisible();

  await page.getByLabel('記帳內容',{exact:true}).fill(`Membership 第二次合成消費 ${name}`);
  await page.getByRole('button',{name:'建立文字草稿',exact:true}).click();
  await dialog.getByLabel('商家',{exact:true}).fill(memberShop);
  const useAdvice=advice.getByRole('button',{name:`使用建議分類 ${memberCategory}`,exact:true});
  await expect(useAdvice).toBeVisible();
  await expect(advice.getByText('你的歷史選擇',{exact:true})).toBeVisible();
  await expect(dialog.getByRole('combobox',{name:'分類',exact:true})).toHaveValue('');
  await useAdvice.click();
  await expect(dialog.getByRole('combobox',{name:'分類',exact:true})).toHaveValue(memberId);
  await dialog.getByRole('combobox',{name:'分類',exact:true}).selectOption(category.id);
  await advice.getByRole('button',{name:'更新建議'}).click();
  await expect(useAdvice).toBeVisible();
  await expect(dialog.getByRole('combobox',{name:'分類',exact:true})).toHaveValue(category.id);
  await advice.scrollIntoViewIfNeeded();
  await page.screenshot({path:info.outputPath('category-suggestions.png')});
  await dialog.getByLabel('金額',{exact:true}).fill('1');
  await dialog.getByRole('button',{name:'加入分類分攤',exact:true}).click();
  await expect(useAdvice).toBeDisabled();
  await advice.getByRole('combobox',{name:'建議套用至',exact:true}).selectOption('1');
  await useAdvice.click();
  await expect(dialog.getByRole('combobox',{name:'分攤分類 1',exact:true})).toHaveValue(category.id);
  await expect(dialog.getByRole('combobox',{name:'分攤分類 2',exact:true})).toHaveValue(memberId);
  await expect(dialog.getByLabel('分攤金額 1',{exact:true})).toHaveValue('1');
  await expect(dialog.getByLabel('分攤金額 2',{exact:true})).toHaveValue('');
  await dialog.getByRole('button',{name:'完成／關閉',exact:true}).click();
  await leave.getByRole('button',{name:'捨棄修改並關閉'}).click();
  await expect(dialog).not.toBeVisible();
});
