import { test, expect } from '@playwright/test';
test('login, configure, run a durable job, logout and log in again', async ({page}, testInfo) => {
  await page.goto('/');
  await expect(page.getByRole('heading', {name:'登入您的財務空間'})).toBeVisible();
  await page.getByLabel('帳號', {exact: true}).fill('alice');
  await page.getByLabel('密碼', {exact: true}).fill('synthetic-test-passphrase');
  await page.getByRole('button', {name:'登入', exact:true}).click();
  await expect(page.getByRole('heading', {name:'從容整理，每一筆生活。'})).toBeVisible();
  await expect(page.locator('body')).not.toContainText('NaN');
  await page.getByRole('button', {name:'偏好設定',exact:true}).click();
  await page.getByLabel('帳本基準幣別').selectOption('USD');
  await page.getByLabel('帳務時區').fill('America/Los_Angeles');
  await page.getByRole('button', {name:'儲存設定'}).click();
  await expect(page.getByText('設定已儲存。')).toBeVisible();
  await page.getByRole('button', {name:'總覽',exact:true}).click();
  await page.getByRole('button', {name:'執行檢查'}).click();
  await expect(page.getByText('背景工作正常')).toBeVisible({timeout:15000});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
  expect(overflow).toBe(false);
  await page.screenshot({path:testInfo.outputPath('overview.png'),fullPage:true});
  await page.getByRole('button', {name:'登出',exact:true}).click();
  await expect(page.getByRole('heading', {name:'登入您的財務空間'})).toBeVisible();
  await page.getByLabel('帳號', {exact:true}).fill('alice');
  await page.getByLabel('密碼', {exact:true}).fill('synthetic-test-passphrase');
  await page.getByRole('button', {name:'登入',exact:true}).click();
  await expect(page.getByRole('heading', {name:'從容整理，每一筆生活。'})).toBeVisible();
  await page.route('**/api/v1/status',route=>route.abort());
  await page.getByRole('button', {name:'偏好設定',exact:true}).click();
  await page.getByRole('button', {name:'儲存設定'}).click();
  await expect(page.getByRole('alert')).toContainText('資料可能已過期');
});
