import { test, expect } from '@playwright/test';

test('bank, card, expense, repayment, refund, immutable chart export', async ({page}, info) => {
  const suffix=info.project.name+'-'+Date.now();
  const bank='銀行-'+suffix, card='信用卡-'+suffix, category='餐飲-'+suffix;
  await page.goto('/');
  await page.getByLabel('帳號',{exact:true}).fill('alice');
  await page.getByLabel('密碼',{exact:true}).fill('synthetic-test-passphrase');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await expect(page.getByRole('heading',{name:'從容整理，每一筆生活。'})).toBeVisible();
  await page.getByRole('button',{name:'帳戶',exact:true}).click();
  for(const [name,kind,balance] of [[bank,'bank','1000'],[card,'credit_card','0']]) {
    await page.getByRole('button',{name:'新增帳戶',exact:true}).click();
    const dialog=page.getByRole('dialog',{name:'新增帳戶',exact:true});
    await dialog.getByLabel('帳戶名稱').fill(name);
    await dialog.getByLabel('帳戶類型').selectOption(kind);
    await dialog.getByLabel(kind==='credit_card'?'期初欠款（溢繳填負數）':'期初餘額',{exact:true}).fill(balance);
    await dialog.getByRole('button',{name:'儲存帳戶'}).click();
    await expect(dialog).not.toBeVisible();
  }
  await page.getByRole('button',{name:'記帳',exact:true}).click();
  await page.getByRole('button',{name:'管理分類'}).click();
  await page.getByLabel('分類名稱').fill(category);
  await page.getByRole('button',{name:'儲存分類'}).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button',{name:'新增交易',exact:true}).click();
  let dialog=page.getByRole('dialog',{name:'新增交易',exact:true});
  await dialog.getByLabel('記帳帳戶').selectOption({label:card+' · USD'});
  await dialog.getByLabel('金額（USD）',{exact:true}).fill('100');
  await dialog.getByRole('combobox',{name:'分類',exact:true}).selectOption({label:category});
  await dialog.getByLabel('商家',{exact:true}).fill('測試商家-'+suffix);
  await dialog.getByRole('button',{name:'確認入帳'}).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button',{name:'新增交易',exact:true}).click();
  dialog=page.getByRole('dialog',{name:'新增交易',exact:true});
  await dialog.getByRole('button',{name:'轉帳',exact:true}).click();
  await dialog.getByLabel('轉出帳戶').selectOption({label:bank+' · USD'});
  await dialog.getByLabel('轉入帳戶').selectOption({label:card+' · USD'});
  await dialog.getByLabel('轉出本金（USD）',{exact:true}).fill('100');
  await dialog.getByRole('button',{name:'確認入帳'}).click();
  await expect(dialog).not.toBeVisible();
  const row=page.getByRole('row').filter({hasText:'測試商家-'+suffix});
  await row.getByRole('button',{name:'退款',exact:true}).click();
  dialog=page.getByRole('dialog',{name:'登記退款'});
  await dialog.getByLabel('金額（USD）',{exact:true}).fill('101');
  await dialog.getByRole('button',{name:'確認入帳'}).click();
  await expect(dialog.getByRole('alert')).toContainText('超過');
  await dialog.getByLabel('金額（USD）',{exact:true}).fill('20');
  await dialog.getByRole('button',{name:'確認入帳'}).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button',{name:'帳戶',exact:true}).click();
  await expect(page.locator('.account-card').filter({hasText:bank})).toContainText('900.00');
  await expect(page.locator('.account-card').filter({hasText:card})).toContainText('-20.00');
  await page.getByRole('button',{name:'總覽',exact:true}).click();
  await page.getByLabel('搜尋商家、備註、標籤').fill(suffix);
  await expect(page.locator('.metric-card').filter({hasText:'支出淨額'})).toContainText('80.00');
  await expect(page.getByRole('img',{name:'月度收入與支出淨額'})).toBeVisible();
  const downloaded=page.waitForEvent('download');
  await page.getByRole('button',{name:'匯出 CSV（ZIP）'}).click();
  const file=await downloaded;
  expect(file.suggestedFilename()).toMatch(/^finance-report-.*\.zip$/);
  await file.saveAs(info.outputPath('synthetic-report.zip'));
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false);
  await page.screenshot({path:info.outputPath('ledger-report.png'),fullPage:true});
});
