import {test, expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import path from 'node:path';

test('receipt upload, HEIC preview, download, reload and removal preserve the transaction', async ({page}, info) => {
  const name = `收據測試-${info.project.name}-${Date.now()}`;
  await page.goto('/');
  await page.getByLabel('帳號', {exact:true}).fill('alice');
  await page.getByLabel('密碼', {exact:true}).fill('synthetic-test-passphrase');
  await page.getByRole('button', {name:'登入',exact:true}).click();
  await expect(page.getByRole('heading',{name:'從容整理，每一筆生活。'})).toBeVisible();
  const csrf = (await page.context().cookies()).find(c=>c.name==='ft_csrf')!.value;
  const headers = {'X-CSRF-Token':csrf, 'Origin':'http://localhost:5173'};
  const create = async (route:string, data:unknown) => {
    const response = await page.request.post('/api/v1'+route, {headers:{...headers,'Idempotency-Key':crypto.randomUUID()},data});
    expect(response.ok(), await response.text()).toBeTruthy();
    return response.json();
  };
  const account = await create('/accounts', {name,kind:'cash',currency:'USD',opening_balance:'50',opening_on:'2026-09-01'});
  const category = await create('/categories', {name,kind:'expense'});
  const txn = await create('/transactions', {kind:'expense',occurred_on:'2026-09-24',account_id:account.id,category_id:category.id,amount:'10',merchant:name});
  await page.getByRole('button',{name:'記帳',exact:true}).click();
  await page.getByLabel('開始日期',{exact:true}).fill('2026-09-01');
  await page.getByLabel('結束日期（含）').fill('2026-09-30');
  await page.getByLabel('搜尋商家、備註、標籤').fill(name);
  const row = page.getByRole('row').filter({hasText:name});
  await row.getByRole('button',{name:'收據',exact:true}).click();
  let dialog = page.getByRole('dialog',{name:'收據附件',exact:true});
  const png = path.resolve('tests/fixtures/receipt.png'), heic = path.resolve('tests/fixtures/receipt.heic');
  await dialog.locator('input[type=file]').setInputFiles([png,heic]);
  await dialog.getByRole('button',{name:'上傳／重試待處理圖片'}).click();
  await expect(dialog.getByRole('heading',{name:'已保存 · 2 張'})).toBeVisible();
  await expect(dialog.getByRole('img',{name:'收據 receipt.heic',exact:true})).toBeVisible();
  await expect(dialog.getByRole('img',{name:'收據 receipt.png',exact:true})).toBeVisible();
  const card = dialog.locator('article').filter({hasText:'receipt.heic'});
  const download = page.waitForEvent('download');
  await card.getByRole('button',{name:'下載原圖'}).click();
  const file = await download;
  await file.saveAs(info.outputPath('download.heic'));
  expect(await readFile(info.outputPath('download.heic'))).toEqual(await readFile(heic));
  await dialog.getByRole('button',{name:'放大預覽 receipt.png'}).click();
  await expect(dialog.locator('.receipt-expanded')).toBeVisible();
  await dialog.getByRole('button',{name:'縮小預覽 receipt.png'}).click();
  await expect(dialog.getByRole('button',{name:'上傳／重試待處理圖片'})).toHaveCount(0);
  await dialog.locator('input[type=file]').setInputFiles({name:'fake.png',mimeType:'image/png',buffer:Buffer.from('<html>not an image</html>')});
  await dialog.getByRole('button',{name:'上傳／重試待處理圖片'}).click();
  await expect(dialog.getByRole('alert')).toContainText('無法解碼圖片');
  await dialog.getByRole('button',{name:'取消上傳 fake.png'}).click();
  expect(await dialog.evaluate(node=>node.scrollWidth>node.clientWidth)).toBe(false);
  await dialog.evaluate(node => {node.scrollTop=0;});
  await page.screenshot({path:info.outputPath('receipt-manager.png'),fullPage:true});
  await dialog.getByRole('button',{name:'完成',exact:true}).click();
  await row.getByRole('button',{name:'收據',exact:true}).click();
  dialog = page.getByRole('dialog',{name:'收據附件',exact:true});
  await expect(dialog.getByRole('heading',{name:'已保存 · 2 張'})).toBeVisible();
  await dialog.locator('article').filter({hasText:'receipt.png'}).getByRole('button',{name:'移除',exact:true}).click();
  await dialog.getByRole('button',{name:'確認移除附件',exact:true}).click();
  await expect(dialog.getByRole('heading',{name:'已保存 · 1 張'})).toBeVisible();
  await dialog.getByRole('button',{name:'完成',exact:true}).click();
  await expect(row).toContainText('10.00');
  const attachmentRows = await (await page.request.get(`/api/v1/transactions/${txn.id}/attachments`)).json();
  expect(attachmentRows).toHaveLength(1);
  const accounts = await (await page.request.get('/api/v1/accounts')).json();
  expect(accounts.find((a:{id:string})=>a.id===account.id).balance).toBe('40');
});
