"""phase1 ledger and report snapshots"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0002_ledger"
down_revision = "0001_phase0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("currency", sa.String(length=12), nullable=False),
        sa.Column("include_in_net_worth", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('bank','cash','credit_card')"),
        sa.CheckConstraint("revision > 0"),
        sa.ForeignKeyConstraint(
            ["currency"],
            ["currencies.code"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_table(
        "categories",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('income','expense')"),
        sa.ForeignKeyConstraint(
            ["owner_id", "parent_id"],
            ["categories.owner_id", "categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_table(
        "fx_quotes",
        sa.Column("currency", sa.String(length=12), nullable=False),
        sa.Column("book_currency", sa.String(length=12), nullable=False),
        sa.Column("effective_on", sa.Date(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rate > 0 AND rate < 1e18"),
        sa.ForeignKeyConstraint(
            ["book_currency"],
            ["currencies.code"],
        ),
        sa.ForeignKeyConstraint(
            ["currency"],
            ["currencies.code"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_quotes_owner_currency_date",
        "fx_quotes",
        ["owner_id", "currency", "effective_on"],
        unique=False,
    )
    op.create_table(
        "report_snapshots",
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_table(
        "transactions",
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_entry_id", sa.Uuid(), nullable=True),
        sa.Column("refund_of_id", sa.Uuid(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column("merchant", sa.String(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('income','expense','transfer','refund','opening','adjustment')"
        ),
        sa.CheckConstraint("status IN ('posted','voided')"),
        sa.CheckConstraint("revision > 0"),
        sa.ForeignKeyConstraint(
            ["owner_id", "id", "current_entry_id"],
            ["journal_entries.owner_id", "journal_entries.transaction_id", "journal_entries.id"],
            name="fk_transaction_current_entry",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "refund_of_id"],
            ["transactions.owner_id", "transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_table(
        "journal_entries",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("entry_role", sa.String(), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("book_currency", sa.String(length=12), nullable=False),
        sa.Column("reverses_entry_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column(
            "creation_txid",
            sa.BigInteger(),
            server_default=sa.text("txid_current()"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("entry_role IN ('original','reversal','replacement')"),
        sa.ForeignKeyConstraint(
            ["book_currency"],
            ["currencies.code"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "reverses_entry_id"],
            ["journal_entries.owner_id", "journal_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "transaction_id"],
            ["transactions.owner_id", "transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
        sa.UniqueConstraint("owner_id", "transaction_id", "id"),
        sa.UniqueConstraint("reverses_entry_id"),
        sa.UniqueConstraint("transaction_id", "revision_no", "entry_role"),
    )
    op.create_index(
        "ix_entries_owner_date", "journal_entries", ["owner_id", "occurred_on"], unique=False
    )
    op.create_table(
        "ledger_accounts",
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("ledger_class", sa.String(), nullable=False),
        sa.Column("currency", sa.String(length=12), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ledger_class IN ('asset','liability','income','expense','equity')"),
        sa.ForeignKeyConstraint(
            ["currency"],
            ["currencies.code"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "account_id"],
            ["accounts.owner_id", "accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id"),
        sa.UniqueConstraint("owner_id", "code"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_table(
        "postings",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("ledger_account_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=12), nullable=False),
        sa.Column("amount_signed", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("book_amount_signed", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("fx_rate", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("component", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "amount_signed <> 0 AND abs(amount_signed) < 1e18 AND abs(book_amount_signed) < 1e18 AND fx_rate > 0 AND fx_rate < 1e18"
        ),
        sa.ForeignKeyConstraint(
            ["currency"],
            ["currencies.code"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "entry_id"],
            ["journal_entries.owner_id", "journal_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "ledger_account_id"],
            ["ledger_accounts.owner_id", "ledger_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id", "line_no"),
        sa.UniqueConstraint("owner_id", "entry_id", "id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_index("ix_postings_ledger", "postings", ["ledger_account_id"], unique=False)
    op.create_table(
        "transaction_splits",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("posting_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("amount_signed", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("book_amount_signed", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "amount_signed <> 0 AND abs(amount_signed) < 1e18 AND abs(book_amount_signed) < 1e18"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "category_id"],
            ["categories.owner_id", "categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "entry_id", "posting_id"],
            ["postings.owner_id", "postings.entry_id", "postings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    # Circular current-entry FK is emitted explicitly after both static tables exist.
    op.create_foreign_key(
        "fk_transaction_current_entry",
        "transactions",
        "journal_entries",
        ["owner_id", "id", "current_entry_id"],
        ["owner_id", "transaction_id", "id"],
    )
    op.execute("""
    CREATE FUNCTION ledger_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION 'immutable financial record' USING ERRCODE='23514'; END $$;
    CREATE FUNCTION ledger_entry_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      NEW.creation_txid := txid_current();
      IF NEW.book_currency IS DISTINCT FROM (SELECT book_currency FROM book_settings WHERE owner_id=NEW.owner_id) THEN
        RAISE EXCEPTION 'book currency mismatch' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE FUNCTION ledger_line_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE journal journal_entries; native_scale integer; book_scale integer;
    BEGIN
      SELECT * INTO STRICT journal FROM journal_entries WHERE id=NEW.entry_id AND owner_id=NEW.owner_id;
      IF journal.creation_txid <> txid_current() OR
        (SELECT xmin::text::bigint FROM journal_entries WHERE id=NEW.entry_id) <> (txid_current() % 4294967296) THEN
        RAISE EXCEPTION 'cannot append to committed journal' USING ERRCODE='23514';
      END IF;
      IF TG_TABLE_NAME = 'postings' THEN
        IF NEW.currency IS DISTINCT FROM (SELECT currency FROM ledger_accounts WHERE id=NEW.ledger_account_id AND owner_id=NEW.owner_id) THEN
          RAISE EXCEPTION 'posting currency mismatch' USING ERRCODE='23514';
        END IF;
        SELECT amount_scale INTO native_scale FROM currencies WHERE code=NEW.currency;
        SELECT amount_scale INTO book_scale FROM currencies WHERE code=journal.book_currency;
        IF round(NEW.amount_signed,native_scale) <> NEW.amount_signed OR
           round(NEW.amount_signed * NEW.fx_rate,book_scale) <> NEW.book_amount_signed OR
           (NEW.currency=journal.book_currency AND NEW.fx_rate<>1) THEN
          RAISE EXCEPTION 'posting precision or conversion mismatch' USING ERRCODE='23514';
        END IF;
      END IF;
      RETURN NEW;
    END $$;
    CREATE FUNCTION ledger_entry_balanced() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE line_count integer; book_sum numeric; currencies_count integer; native_sum numeric;
    BEGIN
      SELECT count(*),sum(book_amount_signed),count(DISTINCT currency),sum(amount_signed)
        INTO line_count,book_sum,currencies_count,native_sum FROM postings WHERE entry_id=NEW.id;
      IF line_count<2 OR book_sum<>0 OR (currencies_count=1 AND native_sum<>0) THEN
        RAISE EXCEPTION 'journal not balanced' USING ERRCODE='23514';
      END IF;
      IF EXISTS (
        SELECT 1 FROM postings p JOIN ledger_accounts l ON l.id=p.ledger_account_id
        LEFT JOIN LATERAL (SELECT count(*) n,sum(amount_signed) amount,sum(book_amount_signed) book
          FROM transaction_splits s WHERE s.posting_id=p.id) s ON true
        WHERE p.entry_id=NEW.id AND
          ((l.ledger_class IN ('income','expense') AND (s.n=0 OR s.amount<>p.amount_signed OR s.book<>p.book_amount_signed))
          OR (l.ledger_class NOT IN ('income','expense') AND s.n<>0))) THEN
        RAISE EXCEPTION 'split sum mismatch' USING ERRCODE='23514';
      END IF;
      IF EXISTS (SELECT 1 FROM transaction_splits s JOIN categories c ON c.id=s.category_id
        JOIN postings p ON p.id=s.posting_id JOIN ledger_accounts l ON l.id=p.ledger_account_id
        JOIN currencies cu ON cu.code=p.currency
        WHERE s.entry_id=NEW.id AND (c.kind<>l.ledger_class OR sign(s.amount_signed)<>sign(p.amount_signed)
          OR round(s.amount_signed,cu.amount_scale)<>s.amount_signed)) THEN
        RAISE EXCEPTION 'split category or precision mismatch' USING ERRCODE='23514';
      END IF;
      IF NEW.entry_role='reversal' THEN
        IF NOT EXISTS (SELECT 1 FROM journal_entries e WHERE e.id=NEW.reverses_entry_id AND e.transaction_id=NEW.transaction_id AND e.occurred_on=NEW.occurred_on AND e.entry_role<>'reversal') OR
          EXISTS (SELECT 1 FROM (SELECT * FROM postings WHERE entry_id=NEW.id) p
            FULL JOIN (SELECT * FROM postings WHERE entry_id=NEW.reverses_entry_id) o USING(line_no)
            WHERE p.id IS NULL OR o.id IS NULL OR p.amount_signed<>-o.amount_signed OR p.book_amount_signed<>-o.book_amount_signed OR p.ledger_account_id<>o.ledger_account_id OR p.fx_rate<>o.fx_rate) THEN
          RAISE EXCEPTION 'invalid reversal' USING ERRCODE='23514';
        END IF;
      END IF;
      RETURN NULL;
    END $$;
    CREATE FUNCTION ledger_transaction_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE current transactions;
    BEGIN
      SELECT * INTO current FROM transactions WHERE id=NEW.id;
      IF (current.status='posted' AND NOT EXISTS(SELECT 1 FROM journal_entries e WHERE e.id=current.current_entry_id AND e.transaction_id=current.id AND e.revision_no=current.revision AND e.entry_role<>'reversal'))
        OR (current.status='voided' AND current.current_entry_id IS NOT NULL) THEN
        RAISE EXCEPTION 'invalid current journal' USING ERRCODE='23514';
      END IF;
      RETURN NULL;
    END $$;
    CREATE FUNCTION ledger_category_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NEW.parent_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM categories c WHERE c.id=NEW.parent_id AND c.owner_id=NEW.owner_id AND c.kind=NEW.kind AND c.parent_id IS NULL AND c.id<>NEW.id) THEN
        RAISE EXCEPTION 'category hierarchy invalid' USING ERRCODE='23514';
      END IF;
      IF TG_OP='UPDATE' AND (NEW.kind<>OLD.kind OR NEW.parent_id IS DISTINCT FROM OLD.parent_id) THEN
        RAISE EXCEPTION 'category structure immutable' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE FUNCTION ledger_account_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NEW.kind<>OLD.kind OR NEW.currency<>OLD.currency OR NEW.owner_id<>OLD.owner_id THEN
        RAISE EXCEPTION 'account identity immutable' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE FUNCTION ledger_binding_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NEW.account_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM accounts a WHERE a.id=NEW.account_id AND a.owner_id=NEW.owner_id AND a.currency=NEW.currency
          AND NEW.ledger_class=CASE WHEN a.kind='credit_card' THEN 'liability' ELSE 'asset' END) THEN
        RAISE EXCEPTION 'ledger account binding mismatch' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER journal_entry_guard BEFORE INSERT ON journal_entries FOR EACH ROW EXECUTE FUNCTION ledger_entry_guard();
    CREATE CONSTRAINT TRIGGER journal_balanced AFTER INSERT ON journal_entries DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION ledger_entry_balanced();
    CREATE CONSTRAINT TRIGGER transaction_current AFTER INSERT OR UPDATE ON transactions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION ledger_transaction_guard();
    CREATE TRIGGER category_guard BEFORE INSERT OR UPDATE ON categories FOR EACH ROW EXECUTE FUNCTION ledger_category_guard();
    CREATE TRIGGER account_guard BEFORE UPDATE ON accounts FOR EACH ROW EXECUTE FUNCTION ledger_account_guard();
    CREATE TRIGGER ledger_binding_guard BEFORE INSERT ON ledger_accounts FOR EACH ROW EXECUTE FUNCTION ledger_binding_guard();
    """)
    for table in (
        "journal_entries",
        "postings",
        "transaction_splits",
        "ledger_accounts",
        "fx_quotes",
        "report_snapshots",
    ):
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION ledger_immutable()"
        )
    for table in ("postings", "transaction_splits"):
        op.execute(
            f"CREATE TRIGGER {table}_guard BEFORE INSERT ON {table} FOR EACH ROW EXECUTE FUNCTION ledger_line_guard()"
        )


def downgrade():
    op.drop_constraint("fk_transaction_current_entry", "transactions", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction_splits")
    op.drop_index("ix_postings_ledger", table_name="postings")
    op.drop_table("postings")
    op.drop_table("ledger_accounts")
    op.drop_index("ix_entries_owner_date", table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_table("transactions")
    op.drop_table("report_snapshots")
    op.drop_index("ix_quotes_owner_currency_date", table_name="fx_quotes")
    op.drop_table("fx_quotes")
    op.drop_table("categories")
    op.drop_table("accounts")
    for name in (
        "ledger_binding_guard",
        "ledger_immutable",
        "ledger_entry_guard",
        "ledger_line_guard",
        "ledger_entry_balanced",
        "ledger_transaction_guard",
        "ledger_category_guard",
        "ledger_account_guard",
    ):
        op.execute(f"DROP FUNCTION IF EXISTS {name}()")
    # ### end Alembic commands ###
